### ISSUE TITLE
-bash: webpalm: command not found

### ISSUE THREAD

**Issue by principal-aaas** [Malwarize/webpalm#16]
From Kali Linux, I'm in the webpalm folder and the webpalm command is highlighted in green and appears executable. I'm in a Google Cloud Shell. Should I try it in a VM instead?

**Comment by yassin-l** [comment]
@principal-aaas  can you share an image of the error?, to see how did you run it?

**Comment by principal-aaas** [comment]
Command:  webpalm -u https://all-around-audit-solutions.com -l1 --live
Error:           -bash: webpalm: command not found

**Comment by yassin-l** [comment]
@principal-aaas, the bash error *"command not found"* is a result of not having "webpalm" in any of the [PATH environment folders](https://www.digitalocean.com/community/tutorials/how-to-view-and-update-the-linux-path-environment-variable). So, if you want to run "webpalm" from its directory, you should add a prefix `./` to the command. It should look like this: `./webpalm -u https://all-around-audit-solutions.com/ -l1 --live`. 

Otherwise, if you want to run it from any location in the system, you need to run the following command **in the same folder as webpalm**: `sudo cp ./webpalm /bin`. Now, you will be able to run it from anywhere in the system.

**Comment by principal-aaas** [comment]
Thanks @yassin-l, it worked. Let the fun begin :)
